version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - pgdbhost
      - jaeger-all-in-one
    #network_mode: "host"
    environment:
      - OTEL_RESOURCE_ATTRIBUTES="service.name=fastapiApp"
#      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger-all-in-one:14268/api/traces
      - OTEL_EXPORTER_OTLP_ENDPOINT=jaeger-all-in-one:14268
  pgdbhost:
    image: postgres:15.2
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapidb
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes: 
      - /var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.44
    #network_mode: "host"
    ports:
      #      - "16685:16685"
      #- "16686:16686"
      #- "14250:14250"
      #- "14268:14268"
        #- "5775:5775/udp"
        #- "6831:6831/udp"
        #- "6832:6832/udp"
        #- "5778:5778"
        #- "9411:9411"
      - 6831:6831/udp # accept jaeger.thrift in compact Thrift protocol used by most current Jaeger clients
      - 6832:6832/udp # accept jaeger.thrift in binary Thrift protocol used by Node.js Jaeger client (because thriftrw npm package does not support compact protocol)
      - 5775:5775/udp # accept zipkin.thrift in compact Thrift protocol (deprecated; only used by very old Jaeger clients, circa 2016)
      - 5778:5778 # serve configs, sampling strategies
      - 16686:16686 # UI port
      - 14269:14269 # collector admin port: health check at / and metrics at /metrics
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=warn
#      - REPORTER_GRPC_HOST_PORT=jaeger-all-in-one:16685
      - MEMORY_MAX_TRACES=100000
      - SPAN_STORAGE_TYPE=badger
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_VALUE=/badger/data
      - BADGER_DIRECTORY_KEY=/badger/key
  otel-collector:
    image: otel/opentelemetry-collector:0.75.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317"          # OTLP over gRPC receiver
    depends_on:
      - jaeger-all-in-one
#    environment:
#      - OTEL_TRACES_EXPORTER=jaeger-all-in-one
#      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger-all-in-one:14250/api/traces
#      - OTEL_PROPAGATORS=jaeger
