version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    network_mode: "host"
  postgres:
    image: postgres:15.2
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapidb
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes: 
      #- ./postgres-data:/var/lib/postgresql/data
      - /var/lib/postgresql/data
      # copy the sql script to create tables
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
