receivers:
#  jaeger:
#    protocols:
#      grpc:
#        endpoint: jaeger-all-in-one:14250
#      thrift_compact:
#        endpoint: jaeger-all-in-one:6831
#      thrift_http:
#        endpoint: jaeger-all-in-one:14268  
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317
#      http:
#        cors:
#          allowed_origins:
#            - "http://*"
#            - "https://*"
#        endpoint: otel-collector:4318
processors:
  batch:
    send_batch_size: 1024
    timeout: 5s
    send_batch_max_size: 11000
exporters:
  otlp:
    endpoint: jaeger-all-in-one:4317
    tls:
      insecure: true
    sending_queue:
      num_consumers: 4
      queue_size: 100
#extensions:
#  health_check:
#  pprof:
#  zpages:
service:
#  extensions: [pprof, zpages, health_check]
  telemetry:
    logs:
      level: "warn"
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
