receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
processors:
  batch:
    send_batch_size: 1024
    timeout: 5s
exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: "0.0.0.0:14250"
    tls:
      insecure: true
    sending_queue:
      num_consumers: 4
      queue_size: 100
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp]
